version: '3.8'

services:
  db:
    image: postgres:16.1
    environment:
      POSTGRES_USER: home
      POSTGRES_PASSWORD: home
      POSTGRES_DB: home
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - default

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: home@home.ru
      PGADMIN_DEFAULT_PASSWORD: home
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - default

volumes:
  pgdata:

networks:
  default:
    driver: bridge