# Generated by Django 5.1.7 on 2025-04-13 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='cart',
            table='cart_new',
        ),
    ]
