# Generated by Django 5.1.7 on 2025-04-13 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_cart_service'),
        ('goods', '0004_alter_products_image_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.products', verbose_name='Товар'),
        ),
    ]
