# Generated by Django 5.1.7 on 2025-04-06 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_alter_products_options_alter_categories_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Неизвестна', max_length=150, unique=True, verbose_name='Страна')),
                ('slug', models.SlugField(blank=True, max_length=200, null=True, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'db_table': 'counrty',
                'ordering': ('id',),
            },
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'ordering': ('id',), 'verbose_name': 'Станок', 'verbose_name_plural': 'Станки'},
        ),
        migrations.AddField(
            model_name='products',
            name='year',
            field=models.IntegerField(default=0, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='products',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='goods.countries', verbose_name='Страна'),
            preserve_default=False,
        ),
    ]
