# Generated by Django 4.2.20 on 2025-05-14 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_alter_products_image_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='name',
            field=models.CharField(default='Неизвестная', max_length=150, unique=True, verbose_name='Страна'),
        ),
    ]
