# Generated by Django 4.2.20 on 2025-05-19 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_alter_countries_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="discount",
        ),
        migrations.RemoveField(
            model_name="products",
            name="price",
        ),
    ]
